In [28]:
#データ処理
import numpy as np
import pandas as pd
import sklearn.datasets

#データ可視化
import matplotlib.pyplot as plt
import matplotlib
%matplotlib inline

In [29]:
#機械学習ライブラリ　scikit-learn
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix, accuracy_score
#from sklearn.datasets import fetch_mldata
from sklearn.datasets import fetch_openml

In [57]:
#機械学習ライブラリ　keras
import keras as ks
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D
from keras.utils import np_utils

In [59]:
from sklearn.datasets import fetch_openml
mnist = fetch_openml('mnist_784', version=1,)

In [60]:
#MNISTデータの読み込み
#mnist=fetch_mldata("'MNIST original'")

In [61]:
y=mnist["target"]

In [35]:
x=mnist["data"]

In [36]:
#訓練、テストセットに分割
x_train, x_test, y_train, y_test=train_test_split(x, y, test_size=0.2, random_state=42)

In [37]:
x_train=x_train[:10000]
y_train=y_train[:10000]

In [38]:
x_test=x_test[:10000]
y_test=y_test[:10000]

In [39]:
x_train=x_train.astype("float32")/255
x_test=x_test.astype("float32")/255


In [40]:
x_train=x_train.reshape(x_train.shape[0],28,28,1)
x_test=x_test.reshape(x_test.shape[0],28,28,1)
print(x_train.shape)
print(x_test.shape)

(10000, 28, 28, 1)
(10000, 28, 28, 1)


In [41]:
#ターゲットデータの確認
print(y_train[0:5])
print(y_test[0:5])

['5' '4' '8' '0' '2']
['8' '4' '8' '7' '7']


In [42]:
#ターゲットデータをクラスベクトルへ変換
y_train=np_utils.to_categorical(y_train,10)
y_test=np_utils.to_categorical(y_test,10)

print(y_train[0:5])
print(y_test[0:5])

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


In [43]:
#Sequentialモデル
model=Sequential()

In [44]:
#入力層と畳み込み層
model.add(Conv2D(8,kernel_size=(3,3),activation="relu",input_shape=(28,28,1)))
#add modelにadd()を使い、畳み込みNNを追加していく
#2Dの畳み込み層　Conv2D
#input_shape 入力層(28,28,1)
#kernel_size 畳み込み層のフィルタサイズ　(3,3)

Instructions for updating:
Colocations handled automatically by placer.


In [45]:
#プール層
model.add(MaxPooling2D(pool_size=(2,2)))
#pool_size (2,2)

In [46]:
#ドロップアウト
model.add(Dropout(0.25))

Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


In [47]:
#全結合層
model.add(Flatten())
model.add(Dense(128,activation="relu"))
#全結合層を2層追加、Flatten()で1つ前の層から出力されたデータを平らなベクトルにする
#Dense()で128ユニットの隠れ層を追加

In [48]:
#出力層
model.add(Dense(10, activation="softmax"))
#出力層は分類するクラスと同数　MNISTは 0～9 の10クラス

In [49]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 8)         80        
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 13, 13, 8)         0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 13, 13, 8)         0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 1352)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 128)               173184    
_________________________________________________________________
dense_2 (Dense)              (None, 10)                1290      
Total params: 174,554
Trainable params: 174,554
Non-trainable params: 0
_________________________________________________________________


In [50]:
#モデル、コンパイル
model.compile(loss="categorical_crossentropy",optimizer="sgd",metrics=["accuracy"])
#compile()メソッド
#損失関数　loss
#最適化アルゴリズム　optimizer
#評価関数　metrics

In [51]:
#モデル訓練
model.fit(x_train, y_train, epochs=50)

Instructions for updating:
Use tf.cast instead.
Epoch 1/50
10000/10000 [==============================] - 5s 453us/step - loss: 1.5400 - acc: 0.5258
Epoch 2/50
10000/10000 [==============================] - 1s 60us/step - loss: 0.5610 - acc: 0.8324
Epoch 3/50
10000/10000 [==============================] - 1s 60us/step - loss: 0.4480 - acc: 0.8607
Epoch 4/50
10000/10000 [==============================] - 1s 60us/step - loss: 0.4049 - acc: 0.8776
Epoch 5/50
10000/10000 [==============================] - 1s 61us/step - loss: 0.3755 - acc: 0.8815
Epoch 6/50
10000/10000 [==============================] - 1s 60us/step - loss: 0.3427 - acc: 0.8943
Epoch 7/50
10000/10000 [==============================] - 1s 59us/step - loss: 0.3199 - acc: 0.9027
Epoch 8/50
10000/10000 [==============================] - 1s 59us/step - loss: 0.3004 - acc: 0.9087
Epoch 9/50
10000/10000 [==============================] - 1s 59us/step - loss: 0.2858 - acc: 0.9133
Epoch 10/50
10000/10000 [==========================

In [52]:
#テストデータで推測結果を出力
cnn_pred=model.predict(x_test)

In [53]:
print(cnn_pred[0])

[4.8976747e-09 4.3042708e-10 6.1682746e-05 7.1368623e-03 9.5799764e-11
 5.2508035e-06 2.7860994e-10 1.5055660e-08 9.9279624e-01 2.3949589e-08]


In [54]:
#推測結果をクラスラベルへ変換
y_pred_CNN=np.argmax(cnn_pred,axis=1)
y_test_CNN=np.argmax(y_test,axis=1)

In [55]:
print(confusion_matrix(y_test_CNN,y_pred_CNN))

[[ 968    0    2    0    0    0    3    1    5    4]
 [   0 1122   10    3    0    3    1    4    7    2]
 [   1    5  934    8    2    1    2    3    8    3]
 [   1    1    6 1004    0    5    1    3    4    9]
 [   4    0    3    0  848    2    7    4    1   37]
 [   2    0    0   17    0  910    2    0    5    1]
 [   5    1    1    0    1   14  937    0    2    0]
 [   0    0    9    1    3    0    0 1021    0   21]
 [   3    1    4   26    1    7    1    3  905   18]
 [   4    3    0    8    2    4    0    5    2 1008]]


In [56]:
print(accuracy_score(y_test_CNN,y_pred_CNN))

0.9657
